# Generated by Django 4.1.7 on 2023-11-11 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user_joined',
            field=models.ManyToManyField(blank=True, related_name='joined_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
