# Generated by Django 4.1.7 on 2023-11-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('chat', '0002_chatroom_user_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='user_joined',
            field=models.ManyToManyField(blank=True, related_name='joined_by', to='blog.profile'),
        ),
    ]
