# Generated by Django 4.1.7 on 2023-11-13 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_chatroom_user_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='user_joined',
            field=models.ManyToManyField(blank=True, related_name='joined_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
