# Generated by Django 4.1.7 on 2023-11-18 20:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_personalchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalChat',
            new_name='PrivateChat',
        ),
    ]
